name: CI/CD Frontend - Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:

        fetch-depth: 0 

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies

      run: npm ci

    - name: 1. Run Lint (ESLint Check)
      run: npm run lint

    - name: 2. Run Tests (Se houver testes unitários)

      run: npm run test 

    - name: 3. SonarCloud Scan and Quality Gate Check

      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      with:
        args: >
          # Substitua 'josiellyr8-byte_dashboard-frontend' pelo seu Project Key real do Frontend
          -Dsonar.organization=josiellyr8-byte 
          -Dsonar.projectKey=josiellyr8-byte_dashboard-frontend

    - name: 4. Build Frontend (Vite)

      run: npm run build

  deploy:
    needs: ci
   
    if: github.ref == 'refs/heads/main' && success() 
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Render Deploy Hook (Static Site)

      run: |
        curl -X POST \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_SERVICE_ID }}/deploys
